# Cl-Gists - Gists API Wrapper for Common Lisp.
[![Build Status](https://circleci.com/gh/Rudolph-Miller/cl-gists.svg?style=shield)](https://circleci.com/gh/Rudolph-Miller/cl-gists)

## API

See [Document](https://rudolph-miller.github.io/cl-gists/overview.html).  
This HTML is generated by [Codex](https://github.com/CommonDoc/codex).


## Author

* Rudolph Miller (chopsticks.tk.ppfm@gmail.com)

## Copyright

Copyright (c) 2015 Rudolph Miller (chopsticks.tk.ppfm@gmail.com)

## License

Licensed under the MIT License.
